name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "feature/ajout-cicd" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # 1er JOB : On vérifie que le code est propre et que les calculs mathématiques sont bons
  quality-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Ruff Check (API only)
        run: uv run ruff check src/insurance_pricing/api/

      - name: MyPy Check (Predict Router only)
        run: uv run mypy src/insurance_pricing/api/routers/predict.py --ignore-missing-imports

      - name: Pytest
        env:
          INSURANCE_PRICING_RUN_ID: base_v2_catboost_two_part_tweedie_1.3_train_smoke_42_classic_none_none
        run: uv run pytest

  # 2ème JOB : On emballe le tout dans Docker (Seulement si le Job 1 a réussi)
  build-and-publish-docker:
    needs: quality-and-tests # <-- C'est ça qui bloque la publication si les tests échouent !
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # GitHub fournit ce mot de passe automatiquement

      - name: Convertir le nom du repo en minuscules (Requis par Docker)
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO }}:latest